### ISSUE TITLE
Crash in on_surface_created

### ISSUE THREAD

**Issue by Boodals** [Aidiakapi/controllinator#1]
When creating a new surface from my mod, your mod crashes due to "surface" being nil on line 114 of control.lua. Looking into it, it seems you are incorrectly adding 1 to the surface_index in order to get the LuaSurface from game.surfaces.
Removing the + 1 on line 113 fixes this issue for me. It should also be corrected in on__pre_surface_deleted, on line 121.

**Comment by Aidiakapi** [comment]
Thanks again for the report, this is fixed and an update has been pushed out :smile:
