### ISSUE TITLE
Crash on clicking start

### ISSUE THREAD

**Issue by jarquafelmu** [Aidiakapi/controllinator#2]
Game crashed when I clicked the start button on the gui for the mod. The following error was generated
` 936.212 Error MainLoop.cpp:1035: Exception at tick 27086926: Error while running event controllinator::on_gui_click (ID 1)
__controllinator__/debug_session.lua:29: cannot start a debug session because entities overlap
 936.212 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event controllinator::on_gui_click (ID 1)
__controllinator__/debug_session.lua:29: cannot start a debug session because entities overlap"`

**Comment by Aidiakapi** [comment]
Hmmm... This error *in theory* should only be able to pop up in multiplayer, where you and a friend are both trying to debug the same entity.

Is this what happened for you?

Regardless of whether that's the case, it obviously shouldn't crash, and I'll work on a patch that makes it so it at the very least doesn't crash. However, any details you could provide about the context whilst you clicked the button would be much appreciated.

---

After looking into it further, I have no clue how this could've happend. The check for overlapping entities is done pre-emptively, and if it occurs, it should print a message.

Could you provide a way for me to reproduce this error?

**Comment by jarquafelmu** [comment]
It was in multiplayer, but I was by myself testing the mod, all I did was open the UI and click start to see what happened, I don't think I was clicking on anything. I'll see if I can get it to crash again.

**Comment by Aidiakapi** [comment]
Did you manage to reproduce this?

**Comment by jarquafelmu** [comment]
Hmm, I'm not sure what the issue was as its not crashing the game anymore. I tried it on a new world, on the world it crashed on in SP and then on the world it crashed on in MP but it didn't crash the game.

Maybe it was just a corrupted game state at the time.

**Comment by Aidiakapi** [comment]
Alright, in that case I'll close this issue. If you encounter any issue like this again in the future, do not hesitate to re-open or create a new issue :). Thanks for your effort!
